version: '3.7'

services:
    #Nginx Service
    webserver:
        image: nginx:latest
        container_name: webserver
        restart: unless-stopped
        depends_on:
            - db
            - app
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/logs:/var/log/nginx/
        networks:
            - frontend

    #PHP Service
    app:
        build: .docker/php
        image: app
        container_name: app
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - backend
            - frontend

    #MySQL Service
    db:
        image: mysql:5.7.22
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - .docker/.mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - backend

networks:
    backend:
    frontend:
